### ISSUE TITLE
Group vite build toolchain in dependabot.yml, and ignore typescript major bumps

### ISSUE THREAD

**Issue by solaawojobi00-bit** [solaawojobi00-bit/netpulse-xlm#145]
Follow-up to #137, which grouped the React packages. Two more classes of bad Dependabot PR remain, and they need different fixes.

## Problem 1: vite and @vitejs/plugin-react are peer-coupled

Same pattern as react/react-dom. `@vitejs/plugin-react` declares a peer range on `vite`, so a major bump to either one alone is unresolvable. Both open PRs fail at `npm ci`, from opposite directions:

**#124** — bumps `vite` 6.4.3 → 8.2.2, leaving `@vitejs/plugin-react` at 4.7.0:

```
npm error While resolving: @vitejs/plugin-react@4.7.0
npm error Found: vite@8.2.2
npm error Could not resolve dependency:
npm error peer vite@"^4.2.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from @vitejs/plugin-react@4.7.0
```

**#128** — bumps `@vitejs/plugin-react` 4.7.0 → 6.1.1, leaving `vite` at 6.4.3:

```
npm error While resolving: @vitejs/plugin-react@6.1.1
npm error Found: vite@6.4.3
npm error Could not resolve dependency:
npm error peer vite@"^8.0.0" from @vitejs/plugin-react@6.1.1
```

plugin-react 4 tops out at vite 7; plugin-react 6 requires vite 8. Neither PR can pass on its own.

### Fix

Add a second group to the `/frontend` entry:

```yaml
      vite:
        patterns:
          - "vite"
          - "@vitejs/plugin-react"
```

`vitest` is deliberately **not** in this group. Its peer range via `@vitest/mocker` is `vite@"^6.0.0 || ^7.0.0 || ^8.0.0"`, which already spans the upgrade, so it does not need to move in lockstep and grouping it would only couple unrelated release cadences.

## Problem 2: typescript 7.0 is not a routine major bump

TypeScript 7.0 is the ground-up Go rewrite of the compiler (typescript-go), not an incremental release of the existing one. It should not be grouped or let through — it needs a deliberate migration, planned on its own.

**#122** (frontend) already demonstrates this is a real behavior change, not a version-resolution problem:

```
src/main.tsx(4,8): error TS2882: Cannot find module or type declarations for
side-effect import of './styles.css'.
```

That requires an ambient declaration or config change in the source — actual migration work.

**#125** (backend) is worth being precise about: it currently **passes every check**, because the backend has no CSS side-effect imports to trip TS2882. The reason to ignore it is not that CI is red; it is that adopting a different compiler implementation across the repo should be one deliberate, reviewed change rather than two independent dependency bumps that happen to land green.

### Fix

Add the same ignore to **both** the `/frontend` and `/backend` entries:

```yaml
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
```

Minor and patch updates to TypeScript continue to flow normally — only majors are held.

## Scope

- `.github/dependabot.yml` only.
- `/frontend`: add the `vite` group alongside the existing `react` group, plus the typescript ignore.
- `/backend`: add the typescript ignore only; nothing else in that entry changes.
- The `github-actions` entry is untouched.
- No application code changes. This does not upgrade vite or TypeScript.

## Follow-up

#124, #128, #122 and #125 will be closed in favour of grouped updates and the ignore rule. #120 (the react half of the #137 split) is closed alongside them.

Note: closing a Dependabot PR by hand registers an implicit ignore for that specific version, so the regrouped vite PR may not reappear on the normal weekly schedule until a newer version ships. Reopening a closed PR and commenting `@dependabot recreate` regenerates it against the new config.

A TypeScript 7 migration should be tracked as its own issue when someone is ready to scope it.
